### ISSUE TITLE
Remove fmt.Println calls in PNGRenderer.Render

### ISSUE THREAD

**Issue by peterhellberg** [windler/dotgraph#1]
It should probably be up to the user of the renderer to decide on what to output?

- https://github.com/windler/dotgraph/blob/101f240b9deb40c9fd0a30d898dd22e874741f81/renderer/pngRenderer.go#L38
- https://github.com/windler/dotgraph/blob/101f240b9deb40c9fd0a30d898dd22e874741f81/renderer/pngRenderer.go#L54

**Comment by windler** [comment]
Good catch. I will remove these prints
